### ISSUE TITLE
Firework Insanity

### ISSUE THREAD

**Issue by DragonARandom** [rainbowphysics/ExtraFireworks#1]
Due to the nature of Railgunner (along with a modded character with the name Sniper), their secondary has no cool down. This means that it can be spammed from the beginning. With Railgunner, I have found that just 2 or 3 firework stuffed heads causes a TON of chaos, even more so when you add pocket I. C. B. M. into the mix. With Sniper (who can spam the secondary MUCH faster) just one is enough to sweep the first stage without too much issue. I do not expect you to do anything about the Sniper one since it is a mod that you are not in control over, but the Railgunner can be spammed.

**Comment by kluberge** [comment]
Fixed in 1.2.5 for both railgunner and sniper
