### ISSUE TITLE
Simulacrum reward bugged

### ISSUE THREAD

**Issue by Bloorix** [rainbowphysics/ExtraFireworks#2]
Hello,
When I play with your mod and I finish a round in the simulacrum, I can't select any reward in the chest that spawn. I get the screen but there is no reward in it. Does the same when I'm not in simulacrum.
I tried to run the game without any mod except yours (and the needed mods) -> Works
Added a few mods (image) -> Doesn't work anymore

Any idea ? Thanks !
![47](https://user-images.githubusercontent.com/109044634/178163393-9682bee6-aabd-4a54-b494-708e9f87f26d.PNG)
![5847](https://user-images.githubusercontent.com/109044634/178163394-f2837c06-835d-46c8-941b-4649b667f46f.PNG)

**Comment by kluberge** [comment]
Hi, I just tested this on my end with only my mod and wasn't able to recreate the bug. What other mods did you have installed?

**Comment by Bloorix** [comment]
All the mod you can see on the first image, plus your mod. All the others mods I have were disabled when I tried to pinpoint what caused the bug.

**Comment by Cptprice7** [comment]
Yeah just noticed this mod was causing the same issue as me, it makes encrusted keys unuseable. I have the first 6 mods installed as well.

**Comment by rainbowphysics** [comment]
Still unable to replicate in 2024. Closing this issue
