### ISSUE TITLE
Will of fireworks proc infinitely every frame when using items that proc "on kill" at a location.

### ISSUE THREAD

**Issue by Darkmega18** [rainbowphysics/ExtraFireworks#4]
Not sure why it happens, but it came to my attention that an issue that plagued me a few times has actually been the will of the fireworks. Your item that procs fireworks on kill.

To reproduce this issue is quite easy and you can see it in action using my modpack code:
0186c627-5d53-4fb9-fb33-a23681805b38

1. Start a game as someone using command and tossing. (so you can choose items and also drop them from the scoreboard screen).

2. Collect some on kill effects. brooch, gas, necklace and wisp etc

3.  Afterwards find "The unforgiveable" a green item, (looks like a slipper with blood on it that procs on kill effects every 8 seconds), or alternatively a forgive me please equipment.

4 notice yourself exploding and proccing effects every 8 seconds or constantly from FMP. 

5. Now. Pick up the will o fireworks next item, and wait for a proc. Your game will suddenly tank and the world will be set aflame around you infinitely. The only way to stop the issue is to drop the will o fireworks from inventory, or not use the FMP/unforgivable.

A red item, which is similar in mechanics called "ceremonial fireworks" which is 25% chance to fire 8 fireworks on kill doesn't have such issue made by [BoneCapTheTweet] for the newtdrop mod.

**Comment by rainbowphysics** [comment]
Think this is the same issue in #3 

Will have to do some testing to get to the bottom of it

**Comment by rainbowphysics** [comment]
Believe this is fixed now as of v1.5.1. 

The solution _seems_ to have been to change null checks (getting rid of all ?. operator usages)
